name: Cross compile and release
on: [pull_request, create, push]

jobs:
  release:
    permissions:
      contents: write
    name: rust ${{ matrix.toolchain }} - os ${{ matrix.platform.os }} - target ${{ matrix.platform.target }}
    strategy:
      matrix:
        platform:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
          - os: ubuntu-22.04
            target: arm-unknown-linux-musleabi
          - os: ubuntu-22.04
            target: i686-unknown-linux-musl
          - os: ubuntu-20.04
            target: arm-unknown-linux-musleabi

        toolchain:
          - stable
          #- beta
          #- nightly
          - 1.74

        bin:
          # move bin to platform???
          - ghaction-rust-toolchain

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
          toolchain: ${{ matrix.toolchain }}

      - name: check rustc version
        run: |
          rustup show
          cargo -V
          rustc -V
          echo ${GITHUB_REF}
          echo ${GITHUB_REF_NAME}
          echo ${GITHUB_REF_TYPE}

      - name: Package as archive
        #if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          else
            tar czvf ../../../${{ matrix.bin }}-${{ matrix.platform.os }}-${{ matrix.platform.target }}-${{ matrix.toolchain }}.tar.gz ${{ matrix.bin }}
          fi
          cd -

      - name: list
        run: |
          ls -lA
          ls -lA ../
          ls -lA target

      - name: Publish release artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform.os }}-${{ matrix.platform.target }}-${{ matrix.toolchain }}
          path: "ghaction-rust-toolchain-*"
      - name: Generate SHA-256
        if: startsWith(github.ref, 'refs/tags/')
        run: shasum -a 256 ${{ matrix.bin }}-${{ matrix.platform.os }}-${{ matrix.platform.target }}-${{ matrix.toolchain }}.tar.gz > ${{ matrix.bin }}-${{ matrix.platform.os }}-${{ matrix.platform.target }}-${{ matrix.toolchain }}.sha256sum
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # token: ${{ secrets.TOKEN1 }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "ghaction-rust-toolchain*"
